### ISSUE TITLE
Questions about pruning functions.

### ISSUE THREAD

**Issue by qzzqzzb** [rkteddy/channel-Lipschitzness-based-pruning#1]
Dear authors,

Congratulations on your excellent work! I found this paper really interesting. But I cannot find any function related to pruning neurons in this repo. Did I miss something?

Thank you!

**Comment by RJ-T** [comment]
Sorry for the missing part of neuron pruning, and we haven't got the time to write detailed explanations of the pruning code. We will update it in a few days and please check it out later.

**Comment by RJ-T** [comment]
We have updated the code today in defense.py.
